import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../Components/Custom/Banner/Index";
import Footer from "../Components/Common/Footer/Index";
import Upcoming from "../Components/Custom/Upcoming/Index";
import Reviews from "../Components/Custom/Reviews/Index";

export default function Home() {
  const reviews = [
    {
      img: "../../../assets/images/shows/show_1.png",
      name: "Akash1",
      country: "Bangladesh",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae in donec in nisi vitae. Vestibulum pellentesque eget laoreet adipiscing.",
    },
    {
      img: "../../../assets/images/shows/show_2.png",
      name: "Akash2",
      country: "Bangladesh",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae in donec in nisi vitae. Vestibulum pellentesque eget laoreet adipiscing.",
    },
    {
      img: "../../../assets/images/shows/show_3.png",
      name: "Akash3",
      country: "Bangladesh",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae in donec in nisi vitae. Vestibulum pellentesque eget laoreet adipiscing.",
    },
    {
      img: "../../../assets/images/shows/show_4.png",
      name: "Akash4",
      country: "Bangladesh",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae in donec in nisi vitae. Vestibulum pellentesque eget laoreet adipiscing.",
    },
    {
      img: "../../../assets/images/shows/show_3.png",
      name: "Akash5",
      country: "Bangladesh",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae in donec in nisi vitae. Vestibulum pellentesque eget laoreet adipiscing.",
    },
    {
      img: "../../../assets/images/shows/show_1.png",
      name: "Akash6",
      country: "Bangladesh",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae in donec in nisi vitae. Vestibulum pellentesque eget laoreet adipiscing.",
    },
    {
      img: "../../../assets/images/shows/show_4.png",
      name: "Akash7",
      country: "Bangladesh",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae in donec in nisi vitae. Vestibulum pellentesque eget laoreet adipiscing.",
    },
    {
      img: "../../../assets/images/shows/show_2.png",
      name: "Akash8",
      country: "Bangladesh",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae in donec in nisi vitae. Vestibulum pellentesque eget laoreet adipiscing.",
    },
    {
      img: "../../../assets/images/shows/show_1.png",
      name: "Akash9",
      country: "Bangladesh",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae in donec in nisi vitae. Vestibulum pellentesque eget laoreet adipiscing.",
    },
    {
      img: "../../../assets/images/shows/show_2.png",
      name: "Akash10",
      country: "Bangladesh",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae in donec in nisi vitae. Vestibulum pellentesque eget laoreet adipiscing.",
    },
    {
      img: "../../../assets/images/shows/show_3.png",
      name: "Akash11",
      country: "Bangladesh",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae in donec in nisi vitae. Vestibulum pellentesque eget laoreet adipiscing.",
    },
    {
      img: "../../../assets/images/shows/show_4.png",
      name: "Akash12",
      country: "Bangladesh",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae in donec in nisi vitae. Vestibulum pellentesque eget laoreet adipiscing.",
    },
    {
      img: "../../../assets/images/shows/show_3.png",
      name: "Akash13",
      country: "Bangladesh",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae in donec in nisi vitae. Vestibulum pellentesque eget laoreet adipiscing.",
    },
    {
      img: "../../../assets/images/shows/show_1.png",
      name: "Akash14",
      country: "Bangladesh",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae in donec in nisi vitae. Vestibulum pellentesque eget laoreet adipiscing.",
    },
    {
      img: "../../../assets/images/shows/show_4.png",
      name: "Akash15",
      country: "Bangladesh",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae in donec in nisi vitae. Vestibulum pellentesque eget laoreet adipiscing.",
    },
    {
      img: "../../../assets/images/shows/show_2.png",
      name: "Akash16",
      country: "Bangladesh",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae in donec in nisi vitae. Vestibulum pellentesque eget laoreet adipiscing.",
    },
  ];
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
          integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <Banner />

      <main className="">
        <Upcoming />
        <Reviews reviews={reviews} />
      </main>

      <Footer />
    </div>
  );
}
